### ISSUE TITLE
Sun Temple not working properly on Xiaomi Redmi Note 3 (5.5 inch, PowerVR)

### ISSUE THREAD

**Issue by gotwig** [NivalVR/UE4Cardboard#1]
Hey, I tried the Sun Temple demo with the plugin, and the left part of the screen is just completly black, while the right side has the distorted lens effect thats needed for VR. Can you help?

I made a new sun temple project, and tested it without the plugin.
Added the plugin folder, and compiled the plugin.
Tested it than on the device.

I have a Xiaomi Redmi Note 3 with 5.5 inches and PowerVR graphics.

Greetings, Eddy

**Comment by zulman** [comment]
Hi,

Unfortuantely there is no Redmi 3 in our office but it's looks strange. Would you be so king to get a screenshot?

**Comment by gotwig** [comment]
Hi,
I did try out the First Person Shooter demo, and there it works all normal and good. Only on the SunTemple demo it works strange.

**Comment by gotwig** [comment]
![12736876_1793270670906098_481131209_o](https://cloud.githubusercontent.com/assets/1532942/13121176/93d90e20-d5b1-11e5-89ac-24856ca64aac.jpg)

**Comment by zulman** [comment]
Got it, thank you! We'll try to solve this out asap.

**Comment by zulman** [comment]
As quick fix attempt - please try to enable mobile hdr.

**Comment by zulman** [comment]
We checked the scene and it turns out that some PostProcessing volumes conflict in the scene. If you delete Global PostProcess and PostProcess_1/2/3 it will work as expected (altough will run a bit slow). Disabling post processing sounds like a horrible idea at first but please keep in mind that VR rendering needs to be done to two eyes per-frame which will already slow down the application pretty well and there is not much room for post-processing to begin with. The only thing that must be enabled for lens distortion to work is MobileHDR. We have updated the README to reflect this.

![photo_2016-02-18_15-49-00](https://cloud.githubusercontent.com/assets/935287/13143833/ab831772-d657-11e5-9d8c-38764bd64000.jpg)

**Comment by cmvrgr** [comment]
I am using a project with BP and first person controller and I am following the Instuctions but I get an error message from Unity:

Message

Plugin 'UE4Cardboard' failed to load because module 'UE4Cardboard' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project

Can you help  ? I am using Mac Version 4.10.2

**Comment by antinnit** [comment]
I have no extra postprocessing volumes in my scene and i only get the right eye rendering.

**Comment by zulman** [comment]
@nkindt will help us with it :)

**Comment by prokshit** [comment]
Hey guys!
i found a solution for the above mentioned problem.
![answer to vr](https://cloud.githubusercontent.com/assets/8560986/13974226/ea61184c-f077-11e5-8240-979ffacb6121.png)
Disable those settings and it should work.

**Comment by engahmedfawzy** [comment]
Hi There,
i followed setup steps, with unreal 4.11 can't get project to open, it gives message first that component 
UE4Editor-UE4Cardboard.dll is missing and ask for rebuild, after click rebuild it gives another message with failed to build the project and i may need to build it manually, after i open the vs 2015 to build project manually it gives some error regarding SimpleMHD class and it cannot inistantiat abstract class, any help please ?

**Comment by engahmedfawzy** [comment]
Hi all, could solve my problem 
i have managed to fix for 4.11 , also changed names of classes to be unique than simplemhd so we now have our own plugin, hope we can fix the continues drift in picture
here my latest fork git
https://github.com/ANGames/UE4Cardboard.git
hope it help

**Comment by kangdonghoon** [comment]
when i played vr preview just play to simpleHMD not changed

**Comment by kangdonghoon** [comment]
how to apply plugin.. ? my editor change nothing....

**Comment by zulman** [comment]
Fix by @engahmedfawzy was merged. Awesome job!

**Comment by zulman** [comment]
@kangdonghoon please describe what you are doing and what you can see in logs?

**Comment by engahmedfawzy** [comment]
@zulman thanks a lot for encourage im software engineer and I think I can help fixing drift issue but problem I don,t understand how simple get its values  and how drift should calculated,  lets continue to drift issue if someone explain to me current calculation equations vs correct ones under the drift opened topics, will be waiting a hand of help :) 
Thanks

**Comment by kangdonghoon** [comment]
![1](https://cloud.githubusercontent.com/assets/11436688/14449286/55e04e32-00ac-11e6-955b-7715da0671d6.PNG) i was applied. like this screen shot 
![2](https://cloud.githubusercontent.com/assets/11436688/14449362/12cc0874-00ad-11e6-95d2-e9fe1d0c805b.PNG) but, didn't change anything 
ditor version 4.11.1 ,visual studio 2015

**Comment by paperq** [comment]
@kangdonghoon 
I use Project Setting ~> Rendering ~> Mobile HDR
Fix this problem.

**Comment by mikekatseli** [comment]
My bad! it works. not sure what i changed but it works haha

First of all thanks for the Plug in but lens distortion not working :( i use unreal 4.11.2 
1. plugin is visible and enabled
2. mobile HDR enabled 
3. PP deleted and disabled 
When i package and run it on my note 5 no lens distortion just split screen like simple hmd maybe i need to download unreal 4.10 or 4.11.1 ?
Please help 

Should i see the lens dis when testing in VR play mode or Mobile mode or just on the device after packing?

**Comment by zerocdv** [comment]
Sorry, but can someone help me out.

I get a:

Missing or incompatible modules in UE4Cardboard plugin 

Plugin UE4Cardboard failed to load because module 'UE4Cardboard' could not be found.

Any solution for this?

Thank you.
