### ISSUE TITLE
Left eye rendering not working

### ISSUE THREAD

**Issue by risoms** [NivalVR/UE4Cardboard#10]
I was able to impliment the plugin on version 4.11, but after changing EHMDDeviceType to DT_OculusRift, I'm only able to see images on the right eye (see example). Any advice on how to fix this?

https://cloud.githubusercontent.com/assets/10383917/14235564/d5e9f240-f9c7-11e5-9b0e-62c2f78555eb.png

**Comment by nkindt** [comment]
Hi risoms,

similar problem came up already some time ago. Can you make sure you followed these steps from the following issue ? https://github.com/NivalVR/UE4Cardboard/issues/1

**Comment by risoms** [comment]
#8 fixed the issue.
