### ISSUE TITLE
FAILED TO LOAD beac. module couldnot be found ----not working on 4.10.4 and 4.11

### ISSUE THREAD

**Issue by mostafa4500** [NivalVR/UE4Cardboard#11]
after coping the plugin in the engine files its appear in the plugins but when i try to activate it its show me this massage ....tried to open a C++project the same result ? plz help the plugin is a savior for me and my little project :D THX Anyway :D

![2016-04-06_15-23-41](https://cloud.githubusercontent.com/assets/18308557/14318118/abe673c4-fc0b-11e5-8f2a-579aca358194.png)
![2016-04-06_15-34-00](https://cloud.githubusercontent.com/assets/18308557/14318455/354a2ca4-fc0d-11e5-90cc-1267ee756a94.png)

**Comment by asahipipi** [comment]
I also meet the same problem....
Is there anyone could please help me  to solve it?

**Comment by zulman** [comment]
Hi guys. Would you be so kind to try with the latest version?

**Comment by mostafa4500** [comment]
4.10.4 and 4.11

**Comment by zulman** [comment]
With the latest version of Plugin i mean. We've updated today.

**Comment by mostafa4500** [comment]
yes i tried to rebuild it and its works thx ... i reinstalled the visual studio and the unreal engine ..its works 
thx 
one extra question when i press vr preivew and trying to look around by the mouse its only moves left and right ....no  up and down ..... is there any way to make the mouse pointer move freely on pc not on mobile...... i really need it for a project that need everything to be rendered by pc [[ ARCHVIZ ]] so ! :D thx for replying .......great plugin :+1:

**Comment by asahipipi** [comment]
Hi zulman:

When I go to check the new plugin, it seems to be still old version now (since 9 days ago) https://github.com/NivalVR/UE4Cardboard

I will try to reinstall the  visual studio and the unreal engine first..

**Comment by zulman** [comment]
Fix was discussed here #15
