### ISSUE TITLE
Doesn't compile on UE4.10.4

### ISSUE THREAD

**Issue by MangiaGelati** [NivalVR/UE4Cardboard#15]
Thanks for all of your work, but sadly I can't compile the plugin.

I've
1) Created a blueprint new project
2) Created an empty new C++ class
3) Copied and pasted the plugin inside the Plugins folder
4) When I restart, it asks me to recompile
5) It fails

If I try to do it manually, it tells there is an error on the override of UpdatePlayerCamera.
Now I am not in front of my pc, but I will write to you more specific info about this error.
Another question: Do the plugin provide support for the magnet?
Thanks you a lot,

Marco

**Comment by MarcoBG** [comment]
![1](https://cloud.githubusercontent.com/assets/7974530/14705269/f3237094-07b8-11e6-80c8-7a25beb6cb4c.png)
![1a](https://cloud.githubusercontent.com/assets/7974530/14705272/f536c886-07b8-11e6-9c74-ca5195cedee5.png)

**Comment by MarcoBG** [comment]
Basically it says UpdatePlayerCamera has the error: "A function attempted to override a non-existent function."

**Comment by nkindt** [comment]
There were recent commits to make the plugin work on 4.11. The problem is most like because of API changes that were introduced in UE from 4.10 to 4.11. Two possible solutions would be to grab the plugin sources of pre-4.11 commit or just switch to UE 4.11 and use the plugin with latest changes.

**Comment by MarcoBG** [comment]
Hi nkindt, thanks, now it works.
But unlucky now I've got this problem:

The Rotation problem:
https://github.com/NivalVR/UE4Cardboard/issues/12

**Comment by YuDad** [comment]
Hi MarcoBG  .Did you solve the problem that you met 27 days ago? Now I have encountered the same problem with you, there is a way to solve it

**Comment by Bjdyyz** [comment]
@MarcoBG Hi MarcoBG .Did you solve the problem that you met 27 days ago? Now I have encountered the same problem with you, there is a way to solve it
