### ISSUE TITLE
No Lens distortion

### ISSUE THREAD

**Issue by risoms** [NivalVR/UE4Cardboard#4]
I've successfully added this plugin onto my project. The VR seems to only be partially working though, specifically there is a left and right screen, but no lens distortion. This is the case from running the project in the editor and as after packaging. Do you have any advice? I'm running UE 4.10.

**Comment by Trojanonator** [comment]
I'm experiencing the same problem. I'm using UE 4.10.4 and testing on Nexus 5. 
This is happening when I have "Use mobile HDR" un-checked.
If it's enabled then game crashes right after startup.

**Comment by nkindt** [comment]
Hi risoms,

MobileHDR must be checked for lens distortion to occur as stated in the README.

**Comment by nkindt** [comment]
Hi Trojanonator,

what does the log/callstack say ?

**Comment by risoms** [comment]
Mobile HDR is enabled for me as well. I'm experiencing no crashing though.

**Comment by risoms** [comment]
Also is the lens distortion supposed to work, as shown on the github page,
in the editor?

**Comment by nkindt** [comment]
Lens distortion doesn't work in the editor. The plugin system doesn't recognize lens distortion for some reasons within the editor but that is a problem on the Epic side and not something we would fix. The screenshot is taken from a Nexus5 via a profiling tool so make sure you to check this on an Android device.

**Comment by risoms** [comment]
Does the lens distortion work on a packaged game running in windows?
- Semeon

**Comment by Trojanonator** [comment]
no it doesnt work in windows

**Comment by risoms** [comment]
I see. Do you have any advice on how to utilize the same lens distortion shown on android devices, to display on a windows pc?

The reason I ask is because I'm hoping to develop on iOS and I want to run my project via server on the pc. I'm hoping to have as much processing work done on the pc. 

In any rate thank you for your time!
- Semeon

**Comment by nkindt** [comment]
The thing is that we use the SimpleHMD plugin developed by Epic but add additional things in there. Therefore this is a problem how Epic handles the device recognition internally and apparently they simply didn't add that feature to be available in the editor or Windows/Mac builds. Only reasonable solution would be to wait until this will be addressed by Epic (maybe 4.11.x code has this fixed already).

**Comment by risoms** [comment]
Ah. Thank you both for the help!
