### ISSUE TITLE
Support for UE 4.11 preview 7

### ISSUE THREAD

**Issue by Irex777** [NivalVR/UE4Cardboard#5]
Hi,
Awesome plug in, but it does not run under 4.11, does not want to compile. Ive tried to add C++ class, but no luck.

**Comment by prokshit** [comment]
Just FYI it ran fine on 4.10.4.
Maybe if you have that version you may want to try that .

**Comment by Irex777** [comment]
Yes, I've try it on 4.10 and it works fine. The problem is that, I do visualizations and their is allot of cool things for static light in 4.11.

**Comment by doomgrave** [comment]
Same problem with 4.11 final build. I have an error compiling the plugin >,<

**Comment by risoms** [comment]
I ran into the same issue but was able to fix it. There have been changes
to the code that plugin is based on (SimpleHMD) in version 4.11. Replace
the differences in VS, then rebuild, and it should work.
- Semeon

**Comment by Irex777** [comment]
@risoms Im not good in c++, can you please specify what needs to be replaced in VS?

**Comment by risoms** [comment]
I'm not near a computer. The code needed to be changed will be clear when you try to build your project. Each error in this plugin will have to be replaced by the 4.11 equivalent in simplehmd.
- Semeon

**Comment by engahmedfawzy** [comment]
Dear Guys i have managed to fix for 4.11 , also changed names of classes to be uniqe than simplemhd so we now have our ownplugin
here my latest fork git
https://github.com/ANGames/UE4Cardboard.git
hope it help

**Comment by zulman** [comment]
Fix by @engahmedfawzy was merged
