### ISSUE TITLE
Eyes changed

### ISSUE THREAD

**Issue by elninogusano** [NivalVR/UE4Cardboard#6]
I have the impression that the eyes are changed position, right on the left and the left on the right. Is this possible?

**Comment by elninogusano** [comment]
If someone have the same issue I've solved it putting a negative value to EyeOffset.

**Comment by Trojanonator** [comment]
where can i find this EyeOffset ?

**Comment by elninogusano** [comment]
In SimpleHMD.cpp change the EyeOffset value to -3.0
