### ISSUE TITLE
Too much drift

### ISSUE THREAD

**Issue by prokshit** [NivalVR/UE4Cardboard#7]
It works nice and great but the image starts to rotate on its own.. Please look into it. There is not drift from official Google cardboard app.

**Comment by zulman** [comment]
Hi,

Yep, in Google Cardboard SDK there is drift compensation system. I think that official Cardboard support in UE4 will be released before we'll be able to implement drift fix in this plugin :)

**Comment by prokshit** [comment]
You think so ^^? it would be great if they did that :package:
