### ISSUE TITLE
Distortion on Desktop Win64?

### ISSUE THREAD

**Issue by danielvuljanic** [NivalVR/UE4Cardboard#8]
Is it possible to get the lens distortion for a desktop game or is it only working for mobile devices?
I'll get a distortion only on the right side, when change EHMDDeviceType to DT_OculusRift:
https://answers.unrealengine.com/questions/384738/how-do-i-invoke-drawdistortionmesh-renderthread.html

**Comment by risoms** [comment]
I'm having the same issue too. The lens distortion is working for me using the EHMDDeviceType change, but I'm only able to see images on the right eye (see example).

![d5e9f240-f9c7-11e5-9b0e-62c2f78555eb](https://cloud.githubusercontent.com/assets/10383917/14235570/f0c85228-f9c7-11e5-91af-0aa1216091ce.png)

**Comment by doomgrave** [comment]
It' could be really usefull. Mainly for who uses Trinus VR like me or any other streaming application

**Comment by danielvuljanic** [comment]
Not an answer but maybe a good input for some testing:
https://answers.unrealengine.com/questions/384277/seperated-viewrect-in-hmd-results-in-black-screen.html
I'll give it a try.

**Comment by risoms** [comment]
The change did not help. I did noticed when using "-stereo on" for a
packaged version of the task, the screen would revert to a SimpleHMD hmd
screen (left and right eye with no distortion).

It seems like the EHMDDeviceType change doesn't have stereo on for some
reason.
- Semeon

**Comment by nkindt** [comment]
Not having a VR preview on desktops is an engine problem. All the plugin does it work on top of the engine and call various engine functions but it can't handle internal engine issues (only use them). The VR preview problem should be hopefully fixed soon by Epic. Till then the only option is to fully build and inspect on a mobile device.

**Comment by risoms** [comment]
The above solution worked, but involved editing the player controller. Using the above selection and the UE VR template fixed the issue.
